name: spent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_view:
    git: https://github.com/ku-spent/photo_view
  amazon_cognito_identity_dart_2: ^0.1.18
  amplify_analytics_pinpoint: ^0.1.0
  amplify_api: ^0.1.0
  amplify_auth_cognito: ^0.1.0
  amplify_datastore: ^0.1.0
  amplify_flutter: ^0.1.0
  animated_icon_button: ^0.4.1
  animated_splash: ^1.0.0
  auto_route: ^0.6.9
  badges: ^1.1.6
  bot_toast: ^4.0.0+1
  cached_network_image: ^2.3.3
  carousel_slider: ^3.0.0
  connectivity: ^3.0.2
  data_connection_checker: ^0.3.4
  equatable: ^2.0.0
  flutter_bloc: ^6.1.0
  flutter_custom_tabs: ^0.6.0
  flutter_html: ^1.3.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_signin_button: ^1.1.0
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.3
  full_screen_image: ^1.0.2
  fuzzy: ^0.3.0
  geolocator: ^7.0.1
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  hive_generator: ^1.0.0
  http: ^0.13.0
  implicitly_animated_reorderable_list: ^0.3.0
  injectable: ^1.2.0
  intl: ^0.17.0
  json_serializable: ^4.0.2
  material_floating_search_bar: ^0.2.6
  md2_tab_indicator: ^1.0.2
  path_provider: ^2.0.1
  persistent_bottom_nav_bar: ^3.1.0
  pull_to_refresh: ^1.6.2
  rxdart: ^0.26.0
  share: ^2.0.0
  smart_select: ^4.3.2
  timeago: ^3.0.1
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.5
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.3
  injectable_generator: ^1.2.0

flutter_native_splash:
  image: assets/images/logo.png
  color: 'ffffff'

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/images/launcher-icon.png'
  image_path_android: 'assets/images/launcher-icon.png'
  adaptive_icon_background: 'assets/images/launcher-background.png'
  adaptive_icon_foreground: 'assets/images/launcher-foreground.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
