# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "<Enter a description>"
    # gradle(
    #     task: 'assemble',
    #     build_type: 'Release'
    # )
    lane :android_beta_app do
        build_number = number_of_commits()
        Dir.chdir "../.." do
            sh("flutter", "packages", "get")
            sh("flutter", "clean")
            sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
        end
        gradle(
            task: 'assemble',
            build_type: 'Release'
        )
        firebase_app_distribution(
            app: "1:628657338913:android:387e59586967e8f6a58160",
            testers: "thitiwat.tha@ku.th",
            release_notes: "Initial test version of the app",
            firebase_cli_path: "/usr/local/bin/firebase",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end