# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "<Enter a description>"
    lane :android_beta_app do
        flutterVersion = flutter_version()
        gradle(
            task: 'bundle',
            build_type: 'Release',
            properties: {
                "versionName" => flutterVersion["version_name"],
                "versionCode" => flutterVersion["version_code"]
            }
        )
        firebase_app_distribution(
            app: "1:628657338913:android:387e59586967e8f6a58160",
            testers: "thitiwat.tha@ku.th, theerathat.n@ku.th",
            release_notes: "Initial test version of the app",
            firebase_cli_path: "/usr/local/bin/firebase",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end